service: starwars-api
frameworkVersion: ^2.19.0
configValidationMode: error
plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-aws-documentation
  - serverless-mocha-plugin
custom:
  documentation:
    version: '1'
    summary: 'Planetas de Star Wars API'
    description: 'Un API de planetas del mundo de Star Wars con la especificacion OpenApi'
    resources:
      -
        path: "api/planetas/{id}"
        description: "Para obtener un planeta por su identificador"
      -
        path: "api/planetas/"
        description: "Para crear un planeta y mostrar"
  table: 'planet-${self:provider.stage}'
  dynamodb:
    stages:
      - dev
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    PLANET_TABLE: ${self:custom.table}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"
functions:
  get:
    handler: resources/api/planet/get.get
    events:
      - http:
          path: api/planetas/{id}
          method: get
  create:
    handler: resources/api/planet/create.create
    events:
      - http:
          path: api/planetas
          method: post
resources:
  Resources:
    planetTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.table}